os: linux

language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/bin

install: true

before_install: |
  if ! [ -x "$HOME/bin/travis-wait-enhanced" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_linux_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
    elif [ "$TRAVIS_OS_NAME" = "osx" ]; then
      wget -qO- "https://github.com/crazy-max/travis-wait-enhanced/releases/download/v1.0.0/travis-wait-enhanced_1.0.0_darwin_x86_64.tar.gz" | tar -zxvf - travis-wait-enhanced
    fi
    mv travis-wait-enhanced "$HOME/bin"
  fi

jobs:
  include:
    - os: linux
      jdk: openjdk8

    - os: osx
      osx_image: xcode9.3

    - name: pr_linux
      os: linux
      jdk: openjdk8
      if: type = pull_request
      script: "travis-wait-enhanced --timeout=60m --interval=4m -- mvn -Dmaven.javadoc.skip=true -B -V install -Prun-its"

    - name: pr_osx
      os: osx
      osx_image: xcode9.3
      if: type = pull_request
      script: "travis-wait-enhanced --timeout=60m --interval=4m -- mvn -Dmaven.javadoc.skip=true -Danimal.sniffer.skip=true -B -V install -Prun-its"

    - name: deploy
      os: linux
      jdk: openjdk8
      if: branch = master AND type = push
      script: "cp .travis.settings.xml $HOME/.m2/settings.xml && travis-wait-enhanced --timeout=60m --interval=4m -- mvn -B -V clean org.apache.maven.plugins:maven-source-plugin:jar-no-fork deploy"

after_success:
  - '[ "$TRAVIS_OS_NAME" = "linux" ] && bash <(curl -s https://codecov.io/bash) -f coverage-reporting/target/site/jacoco-aggregate/jacoco.xml'
