version: '{build}'
init:
- ps: "Add-Type -AssemblyName System.IO.Compression.FileSystem\nif (!(Test-Path -Path \"C:\\apache-maven\" )) {\n        Write-Host \"Downloading Maven $env:MAVEN_VERSION\"\n        (new-object System.Net.WebClient).DownloadFile(\"https://repo1.maven.org/maven2/org/apache/maven/apache-maven/$env:MAVEN_VERSION/apache-maven-$env:MAVEN_VERSION-bin.zip\", \"C:\\apache-maven-$env:MAVEN_VERSION-bin.zip\") \n        [System.IO.Compression.ZipFile]::ExtractToDirectory(\"C:\\apache-maven-$env:MAVEN_VERSION-bin.zip\", \"C:\\apache-maven\")\n      }"
environment:
  MAVEN_VERSION: 3.6.2
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
- cmd: >-
    SET PATH=C:\apache-maven\apache-maven-%MAVEN_VERSION%\bin;%JAVA_HOME%\bin;%PATH%
    mvn --version
cache:
- C:\apache-maven -> appveyor.yml
- C:\Users\appveyor\.m2 -> pom.xml
build_script:
- ps: mvn -B -Prun-its clean install
