# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: master
  pull_request:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B -V install -Prun-its
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
      with:
        verbose: true

  snapshot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # https://github.com/marketplace/actions/maven-setings-action
    - name: Maven Settings
      uses: s4u/maven-settings-action@v2.2.0
      with:
        githubServer: false
        servers: '[{"id": "sonatype-nexus-snapshots, "username": "${{ secrets.sonatype_username }}", "password": "${{ secrets.sonatype_password }}"}]'
    - name: Deploy Snapshot
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: mvn -B -V org.apache.maven.plugins:maven-source-plugin:jar-no-fork deploy -Prun-its
